[program:surdig-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/farhanrobbani/projects/surdig/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=farhanrobbani
numprocs=1
redirect_stderr=true
stdout_logfile=/home/farhanrobbani/projects/surdig/storage/logs/worker.log
stopwaitsecs=3600
